version: "3.9"

# Define the services/containers that will be created
services:
  blog:
    # Buid the Dockerfile in the current directory
    build: .
    # Helps ensure that Docker shuts down processes correctly
    init: true
    # Restart automatically unless the container was stopped by the user
    restart: unless-stopped
    # 1. Bind mount the workspace to /workspace in the container. This must match the "workspaceFolder" in devcontainer.json.
    # 2. Create named volumes for node_modules and pnpm store so that they persist between container restarts and are not shared with the host. This improves performance, especially on Windows and macOS.
    # 3. Create a named volume for pnpm-home to persist pnpm global installs and cache.
    volumes:
      - ..:/workspace
      - node_modules:/workspace/node_modules
      - pnpm-store:/workspace/.pnpm-store
      - pnpm-home:/pnpm-home
    # Keeps the container running so that you can connect to it with VS Code
    command: sleep infinity
    # Expose port 3000 for the Next.js web app
    ports:
      - "3000:3000"
    # 1. Inform pnpm where to put the store and global executables
    # 2. Add pnpm global executables to PATH
    # 3. Tell starship where its config file is
    environment:
      PNPM_STORE_DIR: /workspace/.pnpm-store
      PNPM_HOME: /pnpm-home
      PATH: /pnpm-home:$PATH
      STARSHIP_CONFIG: /workspace/.devcontainer/starship.toml

# Define named volumes
volumes:
  node_modules:
  pnpm-store:
  pnpm-home:
